{% set name = "qpbenchmark" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qpbenchmark-{{ version }}.tar.gz
  sha256: c1bff5b36a7a7c5864874a3b06c31472223440c49fb2b42fb9b8bc720993eaea

build:
  entry_points:
    - qpbenchmark = qpbenchmark.benchmark:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pandas >=1.4.3
    - pip
    - py-cpuinfo >=9.0.0
    - qpsolvers >=4.2.0
    - tqdm >=4.67.1
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6.2
    - pandas >=1.4.3
    - py-cpuinfo >=9.0.0
    - pyarrow >=15.0.0
    - qpsolvers >=4.2.0
    - tabulate >=0.9.0
    - tqdm >=4.67.1

test:
  imports:
    - qpbenchmark
  commands:
    - pip check
    - qpbenchmark --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/qpbenchmark
  summary: Benchmark for quadratic programming solvers available in Python.
  dev_url: https://github.com/qpsolvers/qpbenchmark
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
