{% set name = "qpbenchmark" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qpbenchmark-{{ version }}.tar.gz
  sha256: f41979f1c2def27eb119867d3b9ca8887d03599fa65ebb63d3cf513d48072108

build:
  entry_points:
    - qpbenchmark = qpbenchmark.benchmark:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pandas >=1.4.3
    - pip
    - py-cpuinfo >=9.0.0
    - qpsolvers >=4.2.0
  run:
    - python >=3.8
    - matplotlib-base >=3.6.2
    - pandas >=1.4.3
    - py-cpuinfo >=9.0.0
    - qpsolvers >=4.2.0
    - tabulate >=0.9.0

test:
  imports:
    - qpbenchmark
  commands:
    - pip check
    - qpbenchmark --help
  requires:
    - pip

about:
  home: https://pypi.org/project/qpbenchmark
  summary: Benchmark for quadratic programming solvers available in Python.
  dev_url: https://github.com/qpsolvers/qpbenchmark
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
