{% set name = "qpbenchmark" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qpbenchmark-{{ version }}.tar.gz
  sha256: 699b1b9018e37fb12aa2a51de87e6c60d2a3b5c40a453163752dba3c5575bd8d

build:
  entry_points:
    - qpbenchmark = qpbenchmark.benchmark:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pandas >=1.4.3
    - pip
    - py-cpuinfo >=9.0.0
    - qpsolvers >=4.2.0
  run:
    - python >=3.8
    - matplotlib-base >=3.6.2
    - pandas >=1.4.3
    - py-cpuinfo >=9.0.0
    - qpsolvers >=4.2.0
    - tabulate >=0.9.0

test:
  imports:
    - qpbenchmark
  commands:
    - pip check
    - qpbenchmark --help
  requires:
    - pip

about:
  home: https://pypi.org/project/qpbenchmark
  summary: Benchmark for quadratic programming solvers available in Python.
  dev_url: https://github.com/qpsolvers/qpbenchmark
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
